### ISSUE TITLE
Prevent redundant installation of TW

### ISSUE THREAD

**Issue by kookma** [TheDiveO/TiddlyWikiPluginSkeleton#1]
Hi TheDiveO,

I start using this great app for plugins development and found it quite useful!
But as described in the documentation, when I use skeleton (kickstarter) I have to run the 

npm install

and it will install a fresh Tiddlywiki version! This make the folder big in size!
I wish to know can I change the configuration to use my TW version installed with node.js and prevent
redundant installation of TW in each plugin project folder!

Note: For simplicity I use separate project folder for each plugin! and I do not want to have several plugins in the same folder.

--Mohammad

**Comment by thediveo** [comment]
While I understand your goal, I'm afraid that this is out of scope of a project using npm, because I have to live with what npm does give me. Npm only gives us the fully isolated local install (which is something really good as I learnt over the years of development experience), or a global install. If you need something else, you may try to play tricks with the local `node_modules` directory inside any npm-using project. Maybe you can symlink all copies to a single master installation?

**Comment by kookma** [comment]
Hi TheDiveO,
 Thank you! I actually changed the config file and now I can use TiddlyWikiPluginSkeleton without redundant TW installation.

One time more thank you for TiddlyWikiPluginSkeleton. It gives me great flexibility in developing new plugins.

Best
